// ============================================================================
// LEGALGRAM — AI DOCUMENT GENERATOR (Supabase Edge Function)
// Calls the Claude (Anthropic) API server-side to draft a full, properly
// formatted legal document from the details the chatbot collected.
//
// The ANTHROPIC_API_KEY is read from an edge-function secret and NEVER
// exposed to the frontend.
//
// Deploy:  supabase functions deploy generate-document
// Secret:  supabase secrets set ANTHROPIC_API_KEY=sk-ant-...
// ============================================================================

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

// Sanitize the key: strip anything that isn't a printable ASCII, non-space
// character. This removes stray whitespace, newlines, or invisible Unicode
// characters that can sneak in via copy-paste and break the request headers
// ("not a valid ByteString"). Anthropic keys are all [A-Za-z0-9_-].
const ANTHROPIC_API_KEY = (Deno.env.get("ANTHROPIC_API_KEY") ?? "").replace(
  /[^\x21-\x7E]/g,
  "",
);
const MODEL = "claude-opus-4-8";

interface GenerateRequest {
  /** e.g. "Partnership Agreement", "Non-Disclosure Agreement" */
  documentType?: string;
  /** Key/value details collected from the user (party names, dates, terms…). */
  details?: Record<string, string>;
  /** Optional freeform description if the user typed a request instead. */
  freeform?: string;
}

function buildUserPrompt(req: GenerateRequest): string {
  const title = (req.documentType || "Legal Document").trim();
  const lines: string[] = [];
  lines.push(`Draft a complete, professional "${title}".`);

  if (req.details && Object.keys(req.details).length > 0) {
    lines.push("\nUse these details provided by the user:");
    for (const [key, value] of Object.entries(req.details)) {
      if (value && String(value).trim() && String(value).trim() !== "-") {
        lines.push(`- ${key}: ${value}`);
      }
    }
  }
  if (req.freeform && req.freeform.trim()) {
    lines.push(`\nAdditional context from the user:\n${req.freeform.trim()}`);
  }
  return lines.join("\n");
}

const SYSTEM_PROMPT = `You are an expert legal document drafter for Legalgram, an online legal-document platform.

Your job: produce a COMPLETE, ready-to-review legal document of the type requested, using the details the user provides.

Rules:
- Output ONLY the finished document text. No preamble, no "Here is...", no commentary, no markdown code fences.
- Use clear, conventional legal structure: a centered UPPERCASE title, an intro/recitals paragraph naming the parties and effective date, then numbered sections with UPPERCASE headings (e.g. "1. PURPOSE", "2. TERM"), and a signature block at the end.
- Include the standard clauses a competent lawyer would expect for this document type, even if the user did not mention them (e.g. governing law, severability, entire agreement, dispute resolution, termination) — tailored to the document type.
- Where a needed detail was not provided, insert a clearly marked placeholder in square brackets like [BORROWER NAME] or [___________] rather than inventing false facts.
- Keep language precise and plain enough for a layperson to read, while remaining legally conventional.
- End the document with this exact line on its own:
"This document was generated by Gram AI (Legalgram) and has not been reviewed by a licensed attorney. Please review it carefully before use."`;

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const headers = { ...corsHeaders, "Content-Type": "application/json" };

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers,
    });
  }

  if (!ANTHROPIC_API_KEY) {
    return new Response(
      JSON.stringify({
        error:
          "Server is not configured with an Anthropic API key. Set the ANTHROPIC_API_KEY secret.",
      }),
      { status: 500, headers },
    );
  }

  let body: GenerateRequest;
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid JSON body" }), {
      status: 400,
      headers,
    });
  }

  if (!body.documentType && !body.freeform) {
    return new Response(
      JSON.stringify({ error: "documentType or freeform is required" }),
      { status: 400, headers },
    );
  }

  try {
    const anthropicResp = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 12000,
        thinking: { type: "adaptive" },
        output_config: { effort: "medium" },
        system: SYSTEM_PROMPT,
        messages: [{ role: "user", content: buildUserPrompt(body) }],
      }),
    });

    if (!anthropicResp.ok) {
      const errText = await anthropicResp.text();
      console.error("Anthropic API error:", anthropicResp.status, errText);
      return new Response(
        JSON.stringify({
          error: `AI service error (${anthropicResp.status}). Please try again.`,
          detail: errText.slice(0, 500),
        }),
        { status: 502, headers },
      );
    }

    const data = await anthropicResp.json();

    if (data.stop_reason === "refusal") {
      return new Response(
        JSON.stringify({
          error:
            "The request could not be completed for this document type. Please rephrase or try a different document.",
        }),
        { status: 200, headers },
      );
    }

    // Concatenate all text blocks (skip empty thinking blocks).
    const document = (data.content || [])
      .filter((b: { type: string }) => b.type === "text")
      .map((b: { text: string }) => b.text)
      .join("")
      .trim();

    if (!document) {
      return new Response(
        JSON.stringify({ error: "The AI returned an empty document. Please retry." }),
        { status: 502, headers },
      );
    }

    return new Response(JSON.stringify({ document }), { status: 200, headers });
  } catch (error) {
    console.error("generate-document error:", error);
    return new Response(
      JSON.stringify({
        error: "Unexpected server error while generating the document.",
        detail: String((error as Error)?.message || error),
      }),
      { status: 500, headers },
    );
  }
});
