
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqodjtyzcbjcvsdlzext.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlxb2RqdHl6Y2JqY3ZzZGx6ZXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwMjU4NjYsImV4cCI6MjA5OTYwMTg2Nn0.xayGK2eHVLkaFrHCiftoOYJkk2dkBKhclXccQ5M2ahs";

console.log("Supabase client configuration:", {
  url: SUPABASE_URL,
  keyLength: SUPABASE_PUBLISHABLE_KEY.length,
  keyPrefix: SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + "..."
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Test connection on client initialization
if (typeof window !== 'undefined') {
  supabase.auth.getSession().then(({ data, error }) => {
    console.log("Initial session check:", { 
      hasSession: !!data.session, 
      error: error?.message || 'none' 
    });
  }).catch((error) => {
    console.error("Failed to check initial session:", error);
  });
}
